pipeline:
  identifier: Build_willemjanvanasseldonk_jhttp_1706090953719
  name: Build jhttp
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1706090911781
        repoName: willemjanvanasseldonk/jhttp
  stages:
    - stage:
        identifier: build
        name: build
        caching:
          enabled: true
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: build_java_app
                  type: Run
                  name: Build Java App
                  spec:
                    shell: Sh
                    command: |-
                      echo "Welcome to Harness CI"
                      mvn -B package --file pom.xml
              - step:
                  type: Run
                  name: build
                  identifier: build
                  spec:
                    connectorRef: account.harnessImage
                    image: maven:3.8-jdk-11
                    shell: Sh
                    command: mvn clean package dependency:copy-dependencies
              - step:
                  type: Run
                  name: run test
                  identifier: run_test
                  spec:
                    shell: Sh
                    command: mvn test
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - target/surefire-reports/*.xml
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
